services:
  gateway:
    container_name: c-gateway
    build:
      context: .
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      PORT: 8000
      CUSTOMERS_URL: http://c-customers:8003
      PRODUCTS_URL: http://c-products:8002
      SHOPPING_URL: http://c-shopping:8004
    networks:
      - microservices

networks:
  microservices:
    external: true
